# Generated by Django 5.0.3 on 2024-06-23 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catégorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('composants', models.TextField()),
                ('mode_demploi', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_xof', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('catégorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='gestion_entreprise.catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.IntegerField(default=0)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_entreprise.produit')),
            ],
        ),
    ]
